// ═══════════════════════════════════════════════════════
// MOMO Corn 清新多主题注册表 (themes.js)
// 7 套主题，每套【显式定义完整语义令牌】，不再用工厂粗糙推导。
//
// 令牌规范（新增令牌时必须 7 套主题全部补齐，themes.test.js 会校验）：
//   基础：primary, primaryPressed, primaryDisabled, primarySoft
//   背景：background, backgroundElevated, card, cardPressed, surface, surfaceSoft
//   文字：text, textSecondary, textMuted, textDisabled, textOnPrimary
//   边框：border, borderSoft, borderStrong, divider
//   双人：me, meSoft, meText, partner, partnerSoft, partnerText
//   反馈：success, successSoft, warning, warningSoft, error, errorSoft, info, infoSoft
//   其他：accent, accentSoft, overlay, shadow, skeleton, shimmer
//
// 【禁止】不得把任何令牌硬编码为跨主题同值（阴影/反馈色必须跟随主题）。
// 【禁止】backgroundLavender 等旧命名不得复活；请使用 backgroundElevated。
// ═══════════════════════════════════════════════════════

export const THEME_IDS = {
  DEFAULT: 'default',
  LAVENDER: 'lavender',
  SAKURA: 'sakura',
  MIDNIGHT: 'midnight',
  MATCHA: 'matcha',
  GALAXY: 'galaxy',
  MINIMAL: 'minimal',
};

// 存量偏好里可能保存的旧主题 key —— 唯一允许的兼容出口，统一在 resolveThemeId 处理。
export const LEGACY_THEME_ALIASES = {
  mint: 'matcha',
  peach: 'sakura',
  sky: 'galaxy',
};

export const themes = {
  // ── 暖橙 ☀️ ───────────────────────────────────────────
  default: {
    id: 'default',
    name: '暖橙',
    emoji: '☀️',
    subtitle: '温暖阳光 · 活力橙',
    isDark: false,
    statusBarStyle: 'dark-content',
    previewPrimary: '#FF6B35',
    previewSecondary: '#FF8C5A',
    previewBg: '#FFF8F5',
    colors: {
      primary: '#FF6B35',
      primaryPressed: '#E5571F',
      primaryDisabled: '#FFC9B3',
      primarySoft: '#FFE9DF',
      background: '#FFF8F5',
      backgroundElevated: '#FFFFFF',
      card: '#FFFFFF',
      cardPressed: '#FFF1E9',
      surface: '#FFFFFF',
      surfaceSoft: '#FFF4EE',
      text: '#2D1B00',
      textSecondary: '#8B7355',
      textMuted: '#B7A58E',
      textDisabled: '#D9C8B8',
      textOnPrimary: '#FFFFFF',
      border: '#FFD6C7',
      borderSoft: '#FFE7DC',
      borderStrong: '#FFAE94',
      divider: '#FFEEE6',
      me: '#FF6B35',
      meSoft: '#FFE9DF',
      meText: '#D14E1C',
      partner: '#FF8C5A',
      partnerSoft: '#FFEDE3',
      partnerText: '#D1602F',
      success: '#43A047',
      successSoft: '#E8F5E9',
      warning: '#E8A13D',
      warningSoft: '#FCF1DE',
      error: '#F05A4F',
      errorSoft: '#FDEBE9',
      info: '#3D8BFD',
      infoSoft: '#E8F1FE',
      accent: '#FF8C5A',
      accentSoft: '#FFEDE3',
      overlay: 'rgba(45, 27, 0, 0.42)',
      shadow: '#7A4A2E',
      skeleton: '#F3E4DA',
      shimmer: '#FFF9F4',
    },
  },

  // ── 薰衣草物语 💜 ─────────────────────────────────────
  lavender: {
    id: 'lavender',
    name: '薰衣草物语',
    emoji: '💜',
    subtitle: '温柔梦幻 · 经典紫',
    isDark: false,
    statusBarStyle: 'dark-content',
    previewPrimary: '#8C69CA',
    previewSecondary: '#69B79B',
    previewBg: '#F8F5FF',
    colors: {
      primary: '#8C69CA',
      primaryPressed: '#7554B8',
      primaryDisabled: '#C9B8E6',
      primarySoft: '#EFE9FA',
      background: '#FAF9FC',
      backgroundElevated: '#FFFFFF',
      card: '#FFFFFF',
      cardPressed: '#F3EEFA',
      surface: '#FFFFFF',
      surfaceSoft: '#F4F1F9',
      text: '#27222F',
      textSecondary: '#706879',
      textMuted: '#9A92A6',
      textDisabled: '#C8C2D2',
      textOnPrimary: '#FFFFFF',
      border: '#EAE5EF',
      borderSoft: '#F1EDF6',
      borderStrong: '#CFC4DE',
      divider: '#F0ECF5',
      me: '#8C69CA',
      meSoft: '#EFE9FA',
      meText: '#6B4FAB',
      partner: '#69B79B',
      partnerSoft: '#E7F4EE',
      partnerText: '#478A6E',
      success: '#4CAF6D',
      successSoft: '#E7F4EC',
      warning: '#E8A13D',
      warningSoft: '#FBF1DF',
      error: '#E35D6A',
      errorSoft: '#FBE9EB',
      info: '#5B8DEF',
      infoSoft: '#EAF0FD',
      accent: '#69B79B',
      accentSoft: '#E7F4EE',
      overlay: 'rgba(39, 34, 47, 0.42)',
      shadow: '#3F3454',
      skeleton: '#ECE7F3',
      shimmer: '#F8F6FC',
    },
  },

  // ── 樱花粉 🌸 ─────────────────────────────────────────
  sakura: {
    id: 'sakura',
    name: '樱花粉',
    emoji: '🌸',
    subtitle: '春日浪漫 · 甜心粉',
    isDark: false,
    statusBarStyle: 'dark-content',
    previewPrimary: '#FFB7C5',
    previewSecondary: '#FF8FA3',
    previewBg: '#FFF0F5',
    colors: {
      primary: '#FF8FA3',
      primaryPressed: '#F5708A',
      primaryDisabled: '#FFD3DC',
      primarySoft: '#FFE9EE',
      background: '#FFF0F5',
      backgroundElevated: '#FFFFFF',
      card: '#FFFFFF',
      cardPressed: '#FFF0F4',
      surface: '#FFFFFF',
      surfaceSoft: '#FFF5F8',
      text: '#4A2C3A',
      textSecondary: '#9B6B7A',
      textMuted: '#C49AAA',
      textDisabled: '#E0C4CE',
      textOnPrimary: '#FFFFFF',
      border: '#FFD6E0',
      borderSoft: '#FFE4EC',
      borderStrong: '#F5A9BC',
      divider: '#FDE8EF',
      me: '#FF8FA3',
      meSoft: '#FFE9EE',
      meText: '#D14E68',
      partner: '#FFB7C5',
      partnerSoft: '#FFEEF2',
      partnerText: '#C24A63',
      success: '#57B26A',
      successSoft: '#EAF6EC',
      warning: '#EEA63C',
      warningSoft: '#FCF1DE',
      error: '#EE5A6B',
      errorSoft: '#FCE7EA',
      info: '#6C9BF5',
      infoSoft: '#EBF1FE',
      accent: '#FF8FA3',
      accentSoft: '#FFE5EB',
      overlay: 'rgba(74, 44, 58, 0.42)',
      shadow: '#6E3A4C',
      skeleton: '#F7E3EA',
      shimmer: '#FDF4F7',
    },
  },

  // ── 深夜蓝 🌙（深色主题，反馈色为高亮度变体）────────────
  midnight: {
    id: 'midnight',
    name: '深夜蓝',
    emoji: '🌙',
    subtitle: '星河寂静 · 极客暗黑',
    isDark: true,
    statusBarStyle: 'light-content',
    previewPrimary: '#E94560',
    previewSecondary: '#E94560',
    previewBg: '#1A1A2E',
    colors: {
      primary: '#E94560',
      primaryPressed: '#C9304C',
      primaryDisabled: '#6E2A38',
      primarySoft: '#3A1F30',
      background: '#1A1A2E',
      backgroundElevated: '#22223A',
      card: '#16213E',
      cardPressed: '#1E2A4A',
      surface: '#16213E',
      surfaceSoft: '#202A45',
      text: '#EAEAEA',
      textSecondary: '#A0A0B0',
      textMuted: '#6E6E82',
      textDisabled: '#4A4A5E',
      textOnPrimary: '#FFFFFF',
      border: '#2D4472',
      borderSoft: '#232F4D',
      borderStrong: '#3D5avatar799',
      divider: '#232F4D',
      me: '#E94560',
      meSoft: '#40202E',
      meText: '#FF7A90',
      partner: '#4ECDC4',
      partnerSoft: '#17323A',
      partnerText: '#7FD9D2',
      success: '#5BD98A',
      successSoft: '#14332A',
      warning: '#F5B84C',
      warningSoft: '#3A2E14',
      error: '#FF6B7A',
      errorSoft: '#402028',
      info: '#6EA8FE',
      infoSoft: '#14283F',
      accent: '#E94560',
      accentSoft: '#40202E',
      overlay: 'rgba(0, 0, 0, 0.72)',
      shadow: '#000000',
      skeleton: '#232F4D',
      shimmer: '#2C3A5E',
    },
  },

  // ── 抹茶绿 🍃 ─────────────────────────────────────────
  matcha: {
    id: 'matcha',
    name: '抹茶绿',
    emoji: '🍃',
    subtitle: '清新舒缓 · 自然绿',
    isDark: false,
    statusBarStyle: 'dark-content',
    previewPrimary: '#5B9B6F',
    previewSecondary: '#A8D5A2',
    previewBg: '#F0FFF4',
    colors: {
      primary: '#5B9B6F',
      primaryPressed: '#478257',
      primaryDisabled: '#B4D4BE',
      primarySoft: '#E2F3E7',
      background: '#F0FFF4',
      backgroundElevated: '#FFFFFF',
      card: '#FFFFFF',
      cardPressed: '#EDF8F0',
      surface: '#FFFFFF',
      surfaceSoft: '#F0F8F2',
      text: '#1A3A2A',
      textSecondary: '#5A7A65',
      textMuted: '#88A292',
      textDisabled: '#BED2C4',
      textOnPrimary: '#FFFFFF',
      border: '#C8E6C9',
      borderSoft: '#DAEEE0',
      borderStrong: '#9CC9A5',
      divider: '#E4F2E8',
      me: '#5B9B6F',
      meSoft: '#E2F3E7',
      meText: '#407A52',
      partner: '#86B364',
      partnerSoft: '#E9F3DF',
      partnerText: '#5F8A44',
      success: '#43A047',
      successSoft: '#E6F4E8',
      warning: '#E8A13D',
      warningSoft: '#FAF0DC',
      error: '#E35D6A',
      errorSoft: '#FBE9EB',
      info: '#5B8DEF',
      infoSoft: '#EAF0FD',
      accent: '#A8D5A2',
      accentSoft: '#E9F5E5',
      overlay: 'rgba(26, 58, 42, 0.42)',
      shadow: '#2E4A38',
      skeleton: '#DFEEE3',
      shimmer: '#F4FBF6',
    },
  },

  // ── 星空紫 🌌 ─────────────────────────────────────────
  galaxy: {
    id: 'galaxy',
    name: '星空紫',
    emoji: '🌌',
    subtitle: '深邃梦幻 · 宇宙紫',
    isDark: false,
    statusBarStyle: 'dark-content',
    previewPrimary: '#6C63FF',
    previewSecondary: '#A89CFF',
    previewBg: '#F5F3FF',
    colors: {
      primary: '#6C63FF',
      primaryPressed: '#574EE0',
      primaryDisabled: '#C4BFFF',
      primarySoft: '#EAE7FF',
      background: '#F5F3FF',
      backgroundElevated: '#FFFFFF',
      card: '#FFFFFF',
      cardPressed: '#F0EDFF',
      surface: '#FFFFFF',
      surfaceSoft: '#F4F2FC',
      text: '#2D1B6E',
      textSecondary: '#7B6FA0',
      textMuted: '#A396C4',
      textDisabled: '#CFC8E4',
      textOnPrimary: '#FFFFFF',
      border: '#E0DBFF',
      borderSoft: '#ECE8FF',
      borderStrong: '#BDB3F2',
      divider: '#ECE9FA',
      me: '#6C63FF',
      meSoft: '#EAE7FF',
      meText: '#4F45D6',
      partner: '#A459D1',
      partnerSoft: '#F2E8FA',
      partnerText: '#8443AE',
      success: '#43A047',
      successSoft: '#E7F4E9',
      warning: '#E8A13D',
      warningSoft: '#FAF0DC',
      error: '#E35D6A',
      errorSoft: '#FBE9EB',
      info: '#5B8DEF',
      infoSoft: '#EAF0FD',
      accent: '#A89CFF',
      accentSoft: '#EFEBFF',
      overlay: 'rgba(45, 27, 110, 0.42)',
      shadow: '#33275E',
      skeleton: '#E6E1F7',
      shimmer: '#F6F4FE',
    },
  },

  // ── 极简白 🤍 ─────────────────────────────────────────
  minimal: {
    id: 'minimal',
    name: '极简白',
    emoji: '🤍',
    subtitle: '克制优雅 · 黑白极简',
    isDark: false,
    statusBarStyle: 'dark-content',
    previewPrimary: '#222222',
    previewSecondary: '#444444',
    previewBg: '#FFFFFF',
    colors: {
      primary: '#222222',
      primaryPressed: '#000000',
      primaryDisabled: '#BDBDBD',
      primarySoft: '#EEEEEE',
      background: '#FFFFFF',
      backgroundElevated: '#FFFFFF',
      card: '#F7F7F7',
      cardPressed: '#ECECEC',
      surface: '#F7F7F7',
      surfaceSoft: '#F0F0F0',
      text: '#111111',
      textSecondary: '#888888',
      textMuted: '#AAAAAA',
      textDisabled: '#CCCCCC',
      textOnPrimary: '#FFFFFF',
      border: '#E5E5E5',
      borderSoft: '#EEEEEE',
      borderStrong: '#C8C8C8',
      divider: '#EFEFEF',
      me: '#222222',
      meSoft: '#EEEEEE',
      meText: '#111111',
      partner: '#666666',
      partnerSoft: '#F0F0F0',
      partnerText: '#444444',
      success: '#4C8C50',
      successSoft: '#EAF2EB',
      warning: '#C08A2D',
      warningSoft: '#F7F0E0',
      error: '#C74848',
      errorSoft: '#F8EAEA',
      info: '#4A76C4',
      infoSoft: '#EBF0F8',
      accent: '#444444',
      accentSoft: '#ECECEC',
      overlay: 'rgba(0, 0, 0, 0.42)',
      shadow: '#1A1A1A',
      skeleton: '#EBEBEB',
      shimmer: '#F7F7F7',
    },
  },
};

// 兼容别名导出
export const THEMES = themes;
export const DEFAULT_THEME = themes.default;
export const THEME_LIST = Object.values(themes);

/**
 * 主题 key 规范化（唯一出口）：
 *  - 命中现有主题 => 直接使用
 *  - 命中旧别名（mint/peach/sky）=> 映射到新 id，并标记 wasLegacy
 *  - 其余 => 回退 default 并标记 unknown（调用方负责 console.warn，不静默）
 */
export function resolveThemeId(rawId) {
  if (rawId && themes[rawId]) {
    return { id: rawId, theme: themes[rawId], wasLegacy: false, unknown: false };
  }
  const aliased = rawId ? LEGACY_THEME_ALIASES[rawId] : null;
  if (aliased && themes[aliased]) {
    return { id: aliased, theme: themes[aliased], wasLegacy: true, unknown: false };
  }
  return { id: DEFAULT_THEME.id, theme: DEFAULT_THEME, wasLegacy: false, unknown: Boolean(rawId) };
}

export default themes;
